//! Generate the `meridian.ui.v1` prost types for the **cargo** build.
//!
//! Until now this crate had no cargo codegen path at all: `src/lib.rs` re-exported
//! an `uiview_proto` crate that only Bazel's `rust_prost_library` produces, so
//! `cargo build` could not work here, and `meridian-tui` — which depends on this
//! crate — could not be built or run by cargo either. That is why the TUI has no
//! `[[bin]]`: there was no way to run one.
//!
//! The design is lifted wholesale from `meridian-proto/build.rs`, which already
//! solved this: ONE generator over a SELF-CONTAINED `FileDescriptorSet` (every
//! transitive import inlined by `protoc --include_imports`), with only the SOURCE
//! of those bytes differing between build systems:
//!
//!   * **Bazel** — does not run this file at all. `--cfg=bazel_proto` selects the
//!     `rust_prost_library` (`//rust/uiview:uiview_proto`) instead, so Bazel stays
//!     the authority and adding a proto to `//proto:uiview_proto` still flows
//!     through with no hand-maintained `srcs` list.
//!   * **cargo** (this file) — the committed `proto/gen/meridian_ui_v1.binpb`,
//!     which is that same proto_library's output, checked in.
//!
//! Consequences, all deliberate and all copied from meridian-proto's reasoning:
//!   * cargo needs **no protoc**, no include paths, no WKT resolution and no
//!     vendored copy of `meridian.ui.v1`. `compile_fds` reads bytes; it does not
//!     shell out. Contrast `meridian-mcp`, whose `compile_protos` requires protoc
//!     on `PATH`, and `meridian-k8s`, whose vendored proto copy silently drifted
//!     from 0.5.0 while canonical moved on.
//!   * cargo and Bazel cannot diverge in *shape*: same descriptor set, same prost.
//!   * The committed set is regenerated by `tools/regen_descriptors.sh` and gated
//!     by `tests/descriptor_freshness.rs`, so a stale one cannot merge unnoticed.
//!
//! ⚠ This file is a MERGE-TIME transitional. Once the monorepo lands, `proto/` is
//! in-repo and the descriptor set becomes a build artifact generated from it
//! rather than a checked-in copy — at which point it stops being a version pin
//! while still being what lets cargo work without protoc.

use std::path::PathBuf;

use prost::Message as _;

/// The committed descriptor set — the cargo path's input.
const COMMITTED_FDS: &str = "proto/gen/meridian_ui_v1.binpb";

/// Escape hatch mirroring meridian-proto's `MERIDIAN_PROTO_DESCRIPTOR_SET`: point
/// this at a freshly built set to codegen against something other than the
/// committed bytes (what `tools/regen_descriptors.sh` uses to verify itself).
const FDS_ENV: &str = "MERIDIAN_UIVIEW_DESCRIPTOR_SET";

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Declare the Bazel-only cfg so cargo's check-cfg lint knows it is expected
    // rather than a typo. Bazel sets it via `rustc_flags` and never runs this
    // file; cargo never sets it and always does.
    println!("cargo::rustc-check-cfg=cfg(bazel_proto)");
    println!("cargo:rerun-if-env-changed={FDS_ENV}");
    println!("cargo:rerun-if-changed={COMMITTED_FDS}");

    let fds_path = match std::env::var_os(FDS_ENV) {
        Some(p) => PathBuf::from(p),
        None => PathBuf::from(COMMITTED_FDS),
    };

    if !fds_path.exists() {
        return Err(format!(
            "descriptor set {} not found — run tools/regen_descriptors.sh",
            fds_path.display()
        )
        .into());
    }

    let bytes = std::fs::read(&fds_path)
        .map_err(|e| format!("reading descriptor set {}: {e}", fds_path.display()))?;
    let fds = prost_types::FileDescriptorSet::decode(bytes.as_slice())
        .map_err(|e| format!("decoding descriptor set {}: {e}", fds_path.display()))?;

    // NOTE: `compile_well_known_types()` is deliberately NOT called. Calling it
    // would make prost-build emit its own `google.protobuf.*`; leaving it off —
    // the default — maps those to the `prost-types` crate this crate already
    // depends on. `GrammarPanel.data` is a `google.protobuf.Struct`, and two
    // definitions of it would be distinct types that do not unify, which surfaces
    // as a baffling "expected Struct, found Struct".
    prost_build::Config::new().compile_fds(fds)?;

    Ok(())
}
